In [1]:
import numpy as np
import pandas as pd
from tree import Tree, Node

In [2]:
# Read csv
data_df = pd.read_csv("Iris.csv")
# One-hot encoding, as this is required by the model
data_encoded = pd.get_dummies(data_df, columns=['Species'])
# Split into training, validation, and test sets
train_df = data_encoded.sample(frac=.75, random_state=5)
validate_test_df = data_encoded.drop(train_df.index)

validate_df = validate_test_df.sample(frac=.5, random_state=21)
test_df = validate_test_df.drop(validate_df.index)

# Convert to numpy arrays
train = train_df.values
validate = validate_df.values
test = test_df.values
# Split features from labels
X_train, Y_train = train[:, 1:5], train[:, 5:]
X_val, Y_val = validate[:, 1:5], validate[:, 5:]
X_test, Y_test = test[:, 1:5], test[:, 5:]

In [3]:
# Train the model
myTree = Tree(X_train, Y_train, 8, 5)
myTree.build_tree(myTree.root)

2 0 (1, 3) (111, 3)
2 1 (2, 3) (110, 3)
2 2 (3, 3) (109, 3)
2 3 (4, 3) (108, 3)
2 4 (5, 3) (107, 3)
2 5 (6, 3) (106, 3)
2 6 (7, 3) (105, 3)
2 7 (8, 3) (104, 3)
2 8 (9, 3) (103, 3)
2 9 (10, 3) (102, 3)
2 10 (11, 3) (101, 3)
2 11 (12, 3) (100, 3)
2 12 (13, 3) (99, 3)
2 13 (14, 3) (98, 3)
2 14 (15, 3) (97, 3)
2 15 (16, 3) (96, 3)
2 16 (17, 3) (95, 3)
2 17 (18, 3) (94, 3)
2 18 (19, 3) (93, 3)
2 19 (20, 3) (92, 3)
2 20 (21, 3) (91, 3)
2 21 (22, 3) (90, 3)
2 22 (23, 3) (89, 3)
2 23 (24, 3) (88, 3)
2 24 (25, 3) (87, 3)
2 25 (26, 3) (86, 3)
2 26 (27, 3) (85, 3)
2 27 (28, 3) (84, 3)
2 28 (29, 3) (83, 3)
2 29 (30, 3) (82, 3)
2 30 (31, 3) (81, 3)
2 31 (32, 3) (80, 3)
2 32 (33, 3) (79, 3)
2 33 (34, 3) (78, 3)
2 34 (35, 3) (77, 3)
2 35 (36, 3) (76, 3)
2 36 (37, 3) (75, 3)
2 37 (38, 3) (74, 3)
2 38 (39, 3) (73, 3)
2 39 (40, 3) (72, 3)
2 40 (41, 3) (71, 3)
2 41 (42, 3) (70, 3)
2 42 (43, 3) (69, 3)
2 43 (44, 3) (68, 3)
2 44 (45, 3) (67, 3)
2 45 (46, 3) (66, 3)
2 46 (47, 3) (65, 3)
2 47 (48, 3) (64, 3)

/Users/alex/Projects/ml-algorithms/decision-tree/tree.py:120: RuntimeWarning: invalid value encountered in scalar divide
  right_summation += pow((np.count_nonzero(labels_right[:, k], axis=0) / num_right_datapoints), 2)


In [4]:
myTree.make_prediction(X_val[3])

0
0
0
0
0
0
0
0


1

In [5]:
X_val

array([[5.1, 3.8, 1.5, 0.3],
       [4.7, 3.2, 1.3, 0.2],
       [5.7, 2.8, 4.1, 1.3],
       [4.5, 2.3, 1.3, 0.3],
       [5.4, 3.9, 1.7, 0.4],
       [7.2, 3.2, 6.0, 1.8],
       [6.2, 2.2, 4.5, 1.5],
       [5.5, 3.5, 1.3, 0.2],
       [6.9, 3.1, 5.1, 2.3],
       [5.1, 3.5, 1.4, 0.2],
       [6.1, 2.8, 4.7, 1.2],
       [7.7, 2.8, 6.7, 2.0],
       [6.3, 2.9, 5.6, 1.8],
       [7.6, 3.0, 6.6, 2.1],
       [5.0, 3.6, 1.4, 0.2],
       [6.7, 3.1, 4.4, 1.4],
       [6.5, 3.2, 5.1, 2.0],
       [4.4, 2.9, 1.4, 0.2],
       [6.8, 3.0, 5.5, 2.1]], dtype=object)

In [6]:
Y_val

array([[True, False, False],
       [True, False, False],
       [False, True, False],
       [True, False, False],
       [True, False, False],
       [False, False, True],
       [False, True, False],
       [True, False, False],
       [False, False, True],
       [True, False, False],
       [False, True, False],
       [False, False, True],
       [False, False, True],
       [False, False, True],
       [True, False, False],
       [False, True, False],
       [False, False, True],
       [True, False, False],
       [False, False, True]], dtype=object)

In [7]:
myTree.root.left.labels

array([[False, True, False],
       [False, False, True],
       [False, False, True],
       [True, False, False],
       [False, False, True],
       [False, True, False],
       [True, False, False],
       [False, True, False],
       [True, False, False],
       [False, True, False],
       [False, True, False],
       [False, False, True],
       [False, False, True],
       [False, False, True],
       [True, False, False],
       [True, False, False],
       [False, False, True],
       [False, False, True],
       [True, False, False],
       [True, False, False],
       [False, True, False],
       [False, False, True],
       [True, False, False],
       [False, True, False],
       [False, True, False],
       [False, False, True],
       [False, True, False],
       [False, True, False],
       [False, True, False],
       [False, False, True],
       [True, False, False],
       [False, True, False],
       [False, True, False],
       [True, False, False],
       [False,